import { Component, OnInit, HostListener } from '@angular/core';

declare let $: any;

@Component({
  selector: 'app-unisex',
  templateUrl: './unisex.component.html',
  styleUrls: ['./unisex.component.scss']
})
export class UnisexComponent implements OnInit {
  @HostListener('document:mousemove', ['$event'])
  onMouseMove(e: MouseEvent) {
    var x = e.pageX + 10,
      y = e.pageY + 15;
    var tipw = $('#organs-tip').outerWidth(),
      tiph = $('#organs-tip').outerHeight(),
      x = (x + tipw > $(document).scrollLeft() + $(window).width()) ? x - tipw - (20 * 2) : x
    y = (y + tiph > $(document).scrollTop() + $(window).height()) ? $(document).scrollTop() + $(window).height() - tiph - 10 : y
    $('#organs-tip').css({
      left: x,
      top: y
    })
  }


  @HostListener('click', ['$event.target'])
  onClick(event: any) {
    console.log(this.frt_config[event.id]);
  }

  @HostListener('mousemove', ['$event.target'])
  onMousemove(event: any) {
    if (event.id) {
      var _obj = $('#' + event.id);
      $('#organs-tip').show().html(this.frt_config[event.id].hover);
      _obj.css({
        'fill': this.frt_config[event.id].overColor,
        'fill-opacity': this.frt_config[event.id].overOpacity,
        'stroke': this.frt_config[event.id].outlineOverColor,
        'stroke-opacity': this.frt_config[event.id].outlineOverOpacity
      })
    }
  }

  @HostListener('mouseout', ['$event.target'])
  onMouseout(event: any) {
    if (event.id) {
      $('#organs-tip').hide();
      $('#' + event.id).css({
        'fill': this.frt_config[event.id].upColor,
        'fill-opacity': this.frt_config[event.id].upOpacity,
        'stroke': this.frt_config[event.id].outlineUpColor,
        'stroke-opacity': this.frt_config[event.id].outlineUpOpacity
      })
    }
  }


  frt_config = {
    'frt_1': {
      'hover': '<b><u>HEAD</u></b><br>Write any text and load images<br><img src="assets/images/hover.png">',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': 'red',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',

    },
    'frt_2': {
      'hover': '<b><u>EYE</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_3': {
      'hover': '<b><u>EYE</u></b><br>Write any text and load images<br><img src="assets/images/hover.png">',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_4': {
      'hover': '<b><u>EAR</u></b><br>Write any text and load images<br><img src="assets/images/hover.png">',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_5': {
      'hover': '<b><u>EAR</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_6': {
      'hover': '<b><u>NOSE</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_7': {
      'hover': '<b><u>MOUTH</u></b><br>Write any text and load images<br><img src="assets/images/hover.png">',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_8': {
      'hover': '<b><u>NECK</u></b><br>Change the color of each<br>part independently.',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_9': {
      'hover': '<b><u>CHEST</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_10': {
      'hover': 'ABDOMEN',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_11': {
      'hover': '<b><u>PELVIS</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_12': {
      'hover': '<b><u>PUBIS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_13': {
      'hover': 'SHOULDER',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_14': {
      'hover': '<b><u>SHOULDER</u></b><br>Write any text and load images<br><img src="assets/images/hover.png">',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_15': {
      'hover': '<b><u>ARM</u></b><br>Write any text and load images<br><img src="assets/images/hover.png">',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_16': {
      'hover': '<b><u>ARM</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_17': {
      'hover': '<b><u>ELBOW</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_18': {
      'hover': '<b><u>ELBOW</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_19': {
      'hover': '<b><u>FOREARM</u></b><br>Write any text and load images<br><img src="assets/images/hover.png">',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_20': {
      'hover': '<b><u>FOREARM</u></b><br>Write any text and load images<br><img src="assets/images/hover.png">',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_21': {
      'hover': '<b><u>WRIST</u></b><br>Write any text and load images<br><img src="assets/images/hover.png">',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_22': {
      'hover': '<b><u>WRIST</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_23': {
      'hover': '<b><u>HAND</u></b><br>Write any text and load images<br><img src="assets/images/hover.png">',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_24': {
      'hover': '<b><u>HAND</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_25': {
      'hover': '<b><u>THIGH</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_26': {
      'hover': '<b><u>THIGH</u></b><br>Write any text and load images<br><img src="assets/images/hover.png">',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_27': {
      'hover': '<b><u>KNEE</u></b><br>Write any text and load images<br><img src="assets/images/hover.png">',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_28': {
      'hover': '<b><u>KNEE</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_29': {
      'hover': '<u>LEG</u><br><b>Click to open modal window!</b>',
      'enable': !0,
      'url': '##myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_30': {
      'hover': '<b><u>LEG</u></b><br>Write any text and load images<br><img src="assets/images/hover.png">',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_31': {
      'hover': '<b><u>ANKLE</u></b><br>Change the color of each<br>part independently.',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_32': {
      'hover': '<b><u>ANKLE</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_33': {
      'hover': '<b><u>FOOT</u></b><br>Write any text and load images<br><img src="assets/images/hover.png">',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    },
    'frt_34': {
      'hover': '<b><u>FOOT</u></b><br>Write any text and load images<br><img src="assets/images/hover.png">',
      'enable': !0,
      'url': '#myModal',
      'target': 'modal',
      'upColor': '#FF0000',
      'upOpacity': '0',
      'outlineUpColor': '#ff8080',
      'outlineUpOpacity': '1',
      'overColor': '#FF0000',
      'overOpacity': '0.3',
      'outlineOverColor': '#ff8080',
      'outlineOverOpacity': '1',
      'downColor': '#FF0000',
      'downOpacity': '0.7',
      'outlineDownColor': '#ff8080',
      'outlineDownOpacity': '1',
    }
  }
  constructor() { }

  ngOnInit(): void {

    $(document).ready(function () {
      $('#bck_base').hide().animate({
        'opacity': '0'
      }, 300);
      $('.go_bck').on('click', function () {
        $('#frt_base').hide().animate({
          'opacity': '0'
        }, 300);
        $('#bck_base').show().animate({
          'opacity': '1'
        }, 300)
      });
      $('.go_frt').on('click', function () {
        $('#bck_base').hide().animate({
          'opacity': '0'
        }, 300);
        $('#frt_base').show().animate({
          'opacity': '1'
        }, 300)
      })
    });

  }
}
