export const MALE_CONFIG_SETTINGS = {
    'title_desc' : 'Human muscular system',
    'ft_1': {
        'hover': '<b><u>STERNOCLEIDOMASTOID</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': 'red',
        'upOpacity': '0',
        'outlineUpColor': 'red',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_2': {
        'hover': '<b><u>STERNOCLEIDOMASTOID</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_3': {
        'hover': '<b><u>TRAPEZIUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_4': {
        'hover': '<b><u>TRAPEZIUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_5': {
        'hover': '<b><u>DELTOID</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_6': {
        'hover': '<b><u>DELTOID</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_7': {
        'hover': '<b><u>PECTORALIS MAJOR</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_8': {
        'hover': '<b><u>PECTORALIS MAJOR</u></b><br>Change the color of each<br>part independently.',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_9': {
        'hover': '<b><u>RECTUS ABDOMINIS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_10': {
        'hover': 'SERRATUS ANTERIOR',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_11': {
        'hover': '<b><u>SERRATUS ANTERIOR</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_12': {
        'hover': '<b><u>ABDOMINAL EXTERNAL OBLIQUE</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_13': {
        'hover': 'ABDOMINAL EXTERNAL OBLIQUE',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_14': {
        'hover': '<b><u>BICEPS BRACHII</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_15': {
        'hover': '<b><u>BICEPS BRACHII</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_16': {
        'hover': '<b><u>BRACHIORADIALIS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_17': {
        'hover': '<b><u>BRACHIORADIALIS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_18': {
        'hover': '<b><u>FLEXOR CARPI RADIALIS</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_19': {
        'hover': '<b><u>FLEXOR CARPI RADIALIS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_20': {
        'hover': '<b><u>PALMARIS LONGUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_21': {
        'hover': '<b><u>PALMARIS LONGUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_22': {
        'hover': '<b><u>GLUTEUS MEDIUS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_23': {
        'hover': '<b><u>GLUTEUS MEDIUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_24': {
        'hover': '<b><u>VASTUS LATERALIS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_25': {
        'hover': '<b><u>VASTUS LATERALIS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_26': {
        'hover': '<u>RECTUS FEMORIS</u><br><b>Click to open modal window!</b>',
        'enable': !0,
        'url': '#mymodal',
        'target': 'modal',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_27': {
        'hover': '<b><u>RECTUS FEMORIS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_28': {
        'hover': '<b><u>SARTORIUS</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_29': {
        'hover': '<b><u>SARTORIUS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_30': {
        'hover': '<b><u>PECTINEUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_31': {
        'hover': '<b><u>PECTINEUS</u></b><br>Change the color of each<br>part independently.',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_32': {
        'hover': '<b><u>ADDUCTOR LONGUS</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_33': {
        'hover': '<b><u>ADDUCTOR LONGUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_34': {
        'hover': '<b><u>VASTUS MEDIALIS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_35': {
        'hover': '<b><u>VASTUS MEDIALIS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_36': {
        'hover': '<b><u>GRACILIS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_37': {
        'hover': '<b><u>GRACILIS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_38': {
        'hover': '<b><u>GASTROCNEMIUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_39': {
        'hover': '<b><u>GASTROCNEMIUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_40': {
        'hover': '<b><u>SOLEUS</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_41': {
        'hover': '<b><u>SOLEUS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_42': {
        'hover': '<b><u>TIBIALIS ANTERIOR</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_43': {
        'hover': '<b><u>TIBIALIS ANTERIOR</u></b><br>Change the color of each<br>part independently.',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_44': {
        'hover': '<b><u>PERONEUS LONGUS</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'ft_45': {
        'hover': '<b><u>PERONEUS LONGUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_1': {
        'hover': '<b><u>TRAPEZIUS</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': 'red',
        'upOpacity': '0',
        'outlineUpColor': 'red',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_2': {
        'hover': '<b><u>INFRASPINATUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_3': {
        'hover': '<b><u>INFRASPINATUS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_4': {
        'hover': '<b><u>TERES MAJOR</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_5': {
        'hover': '<b><u>TERES MAJOR</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_6': {
        'hover': '<b><u>LATISSIMUS DORSI</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_7': {
        'hover': '<b><u>LATISSIMUS DORSI</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_8': {
        'hover': '<b><u>DELTOID</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_9': {
        'hover': '<b><u>DELTOID</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_10': {
        'hover': '<b><u>TRICEPS BRACHII</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_11': {
        'hover': '<b><u>TRICEPS BRACHII</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_12': {
        'hover': '<b><u>EXTENSOR CARPI ULNARIS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_13': {
        'hover': '<b><u>EXTENSOR CARPI ULNARIS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_14': {
        'hover': '<b><u>FLEXOR CARPI ULNARIS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_15': {
        'hover': '<b><u>FLEXOR CARPI ULNARIS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_16': {
        'hover': '<b><u>GLUTEUS MEDIUS</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_17': {
        'hover': '<b><u>GLUTEUS MEDIUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_18': {
        'hover': '<b><u>GLUTEUS MAXIMUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_19': {
        'hover': '<b><u>GLUTEUS MAXIMUS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_20': {
        'hover': '<b><u>VASTUS LATERALIS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_21': {
        'hover': '<b><u>VASTUS LATERALIS</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_22': {
        'hover': '<b><u>BICEPS FEMORIS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_23': {
        'hover': '<b><u>BICEPS FEMORIS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_24': {
        'hover': '<b><u>SEMITENDINOSUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_25': {
        'hover': '<b><u>SEMITENDINOSUS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_26': {
        'hover': '<b><u>SEMIMEMBRANOSUS</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_27': {
        'hover': '<b><u>SEMIMEMBRANOSUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_28': {
        'hover': '<b><u>ADDUCTOR MAGNUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_29': {
        'hover': '<b><u>ADDUCTOR MAGNUS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_30': {
        'hover': '<b><u>GASTROCNEMIUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',
    },
    'bk_31': {
        'hover': '<b><u>GASTROCNEMIUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        //'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#FF0000',
        'outlineDownOpacity': '1',

    }
}