export const ORGAN_CONFIG_SETTINGS = {
    'title_desc' : 'Human organ system',
    'ext_1': {
        'hover': '<b><u>HEAD</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_2': {
        'hover': '<b><u>EYE</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_3': {
        'hover': '<b><u>EYE</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_4': {
        'hover': '<b><u>EAR</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_5': {
        'hover': '<b><u>EAR</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_6': {
        'hover': '<b><u>NOSE</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_7': {
        'hover': '<b><u>MOUTH</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_8': {
        'hover': '<b><u>NECK</u></b><br>Change the color of each<br>part independently.',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_9': {
        'hover': '<b><u>CHEST</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_10': {
        'hover': 'ABDOMEN',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_11': {
        'hover': '<b><u>PELVIS</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_12': {
        'hover': '<b><u>PUBIS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_13': {
        'hover': 'SHOULDER',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_14': {
        'hover': '<b><u>SHOULDER</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_15': {
        'hover': '<b><u>ARM</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_16': {
        'hover': '<b><u>ARM</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_17': {
        'hover': '<b><u>ELBOW</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_18': {
        'hover': '<b><u>ELBOW</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_19': {
        'hover': '<b><u>FOREARM</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_20': {
        'hover': '<b><u>FOREARM</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_21': {
        'hover': '<b><u>WRIST</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_22': {
        'hover': '<b><u>WRIST</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_23': {
        'hover': '<b><u>HAND</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_24': {
        'hover': '<b><u>HAND</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_25': {
        'hover': '<b><u>THIGH</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_26': {
        'hover': '<b><u>THIGH</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_27': {
        'hover': '<b><u>KNEE</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_28': {
        'hover': '<b><u>KNEE</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_29': {
        'hover': '<u>LEG</u><br><b>Click to open modal window!</b>',
        'enable': !0,
        'url': '#mymodal',
        'target': 'modal',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_30': {
        'hover': '<b><u>LEG</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_31': {
        'hover': '<b><u>ANKLE</u></b><br>Change the color of each<br>part independently.',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_32': {
        'hover': '<b><u>ANKLE</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_33': {
        'hover': '<b><u>FOOT</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'ext_34': {
        'hover': '<b><u>FOOT</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'int_1': {
        'hover': '<b><u>BRAIN</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': 'red',
        'upOpacity': '0',
        'outlineUpColor': 'red',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.6',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'int_2': {
        'hover': '<b><u>LARYNX</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.6',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'int_3': {
        'hover': '<b><u>THYROID</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.6',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'int_4': {
        'hover': '<b><u>TRACHEA</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.6',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'int_5': {
        'hover': '<b><u>LUNGS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.6',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'int_6': {
        'hover': '<b><u>STOMACH</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.6',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'int_7': {
        'hover': '<b><u>HEART</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.6',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'int_8': {
        'hover': '<b><u>SPLEEN</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.6',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'int_9': {
        'hover': '<b><u>LIVER</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.6',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'int_10': {
        'hover': '<b><u>COLON - LARGE INTESTINE</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.6',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'int_11': {
        'hover': '<b><u>SMALL INTESTINE</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA/',
        'target': 'same_window',
        'upColor': '#ff8080',
        'upOpacity': '0',
        'outlineUpColor': '#ff8080',
        'outlineUpOpacity': '1',
        'overColor': '#FF0000',
        'overOpacity': '0.6',
        'outlineOverColor': '#ff8080',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    }
}
