export const  SKELETON_CONFIG_SETTINGS = {
    'title_desc' : 'Human skeleton',
    'b1': {
        'hover': '<b><u>SKULL</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': 'red',
        'upOpacity': '0',
        'outlineUpColor': 'red',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b2': {
        'hover': '<b><u>SPINE</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b3': {
        'hover': '<b><u>SACRUM</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b4': {
        'hover': '<b><u>PELVIS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b5': {
        'hover': '<b><u>RIBS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b6': {
        'hover': '<b><u>STERNUM</u></b><br>You can set any part as:<br><b>"active"</b> > clickable or<br><span style="color: #808080;"><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b7': {
        'hover': '<b><u>RIGHT CLAVICLE</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b8': {
        'hover': '<b><u>LEFT CLAVICLE</u></b><br>Change the color of each<br>part independently.',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b9': {
        'hover': '<b><u>RIGHT SCAPULA</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b10': {
        'hover': 'LEFT SCAPULA',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b11': {
        'hover': '<b><u>RIGHT HUMERUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': 'red',
        'upOpacity': '0',
        'outlineUpColor': 'red',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b12': {
        'hover': '<b><u>LEFT HUMERUS</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b13': {
        'hover': '<b><u>RIGHT RADIUS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b14': {
        'hover': '<b><u>LEFT RADIUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b15': {
        'hover': '<b><u>RIGHT ULNA</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b16': {
        'hover': '<b><u>LEFT ULNA</u></b><br>You can set any part as:<br><b>"active"</b> > clickable or<br><span style="color: #808080;"><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b17': {
        'hover': '<b><u>RIGHT HAND</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b18': {
        'hover': '<b><u>LEFT HAND</u></b><br>Change the color of each<br>part independently.',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b19': {
        'hover': '<u>RIGHT FEMUR</u><br><b>Click to open modal window!</b>',
        'enable': !0,
        'url': '#mymodal',
        'target': 'modal',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b20': {
        'hover': 'LEFT FEMUR',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b21': {
        'hover': '<b><u>RIGHT PATELLA</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': 'red',
        'upOpacity': '0',
        'outlineUpColor': 'red',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b22': {
        'hover': '<b><u>LEFT PATELLA</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b23': {
        'hover': '<b><u>RIGHT TIBIA</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b24': {
        'hover': '<b><u>LEFT TIBIA</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b25': {
        'hover': '<b><u>RIGHT FIBULA</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b26': {
        'hover': '<b><u>LEFT FIBULA</u></b><br>You can set any part as:<br><b>"active"</b> > clickable or<br><span style="color: #808080;"><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b27': {
        'hover': '<b><u>RIGHT FOOT</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b28': {
        'hover': '<b><u>LEFT FOOT</u></b><br>Change the color of each<br>part independently.',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b29': {
        'hover': '<b><u>RIGHT CARPALS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b30': {
        'hover': 'LEFT CARPALS',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b31': {
        'hover': '<b><u>RIGHT METACARPALS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': 'red',
        'upOpacity': '0',
        'outlineUpColor': 'red',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b32': {
        'hover': '<b><u>LEFT METACARPALS</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b33': {
        'hover': '<b><u>RIGHT HAND PHALANGES</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b34': {
        'hover': '<b><u>LEFT HAND PHALANGES</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b35': {
        'hover': '<b><u>RIGHT CALCANEUS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b36': {
        'hover': '<b><u>LEFT CALCANEUS</u></b><br>You can set any part as:<br><b>"active"</b> > clickable or<br><span style="color: #808080;"><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b37': {
        'hover': '<b><u>RIGHT TALUS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b38': {
        'hover': '<b><u>LEFT TALUS</u></b><br>Change the color of each<br>part independently.',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b39': {
        'hover': '<b><u>RIGHT TARSALS</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b40': {
        'hover': 'LEFT TARSALS',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b41': {
        'hover': '<b><u>RIGHT METATARSALS</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': 'red',
        'upOpacity': '0',
        'outlineUpColor': 'red',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b42': {
        'hover': '<b><u>LEFT METATARSALS</u></b><br><span style="color: #808080;">Set any part as:<br><b>"active"</b> > clickable or<br><b>"inactive"</b> > not clickable.</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b43': {
        'hover': '<b><u>RIGHT FOOT PHALANGES</u></b><br><span style="color: #ff1a75;">*Link each part to any webpage*</span>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    },
    'b44': {
        'hover': '<b><u>LEFT FOOT PHALANGES</u></b><br>Write any text and load images<br>',
        'enable': !0,
        'url': 'NA',
        'target': 'same_window',
        'upColor': '#FF0000',
        'upOpacity': '0',
        'outlineUpColor': '#FF0000',
        'outlineUpOpacity': '0.5',
        'overColor': '#FF0000',
        'overOpacity': '0.3',
        'outlineOverColor': '#FF0000',
        'outlineOverOpacity': '1',
        'downColor': '#FF0000',
        'downOpacity': '0.7',
        'outlineDownColor': '#ff8080',
        'outlineDownOpacity': '1',
    }
}